package dev.tools.annotationprocessor.core.reflection;

import com.squareup.javapoet.ClassName;
import dev.tools.annotationprocessor.core.annotations.CXSpringRestCrudApi;
import dev.tools.annotationprocessor.core.annotations.entity.CXColumn;
import dev.tools.annotationprocessor.core.annotations.entity.CXId;
import java.lang.reflect.Field;
import java.util.Arrays;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.TypeElement;

/**
 * ClassReflectionTool class Util class to play with reflection and annotation processor elements
 *
 * @author josue.rojas
 */
public class ClassReflectionTool {

  /**
   * Get declared field using TypeElement instance
   *
   * @param typeElement type element created by annotation processor
   * @return declared fields
   */
  public static List<? extends Element> getDeclaredFields(final TypeElement typeElement) {
    return typeElement.getEnclosedElements().stream()
        .filter(e -> ElementKind.FIELD.equals(e.getKind()))
        .collect(Collectors.toList());
  }

  /**
   * Get declared fields using java simple class
   *
   * @param clazz Java simple clazz
   * @return
   */
  public static List<Field> getDeclaredFields(final Class<?> clazz) {
    return Arrays.asList(clazz.getDeclaredFields());
  }

  /**
   * Get id field using java simple class
   *
   * @param clazz java simple class
   * @throws IllegalStateException when id field does not exist for CX annotated class
   * @return annotated field id
   */
  public static Field getIdField(final Class<?> clazz) {

    final Optional<Field> idFieldOptional =
        Arrays.stream(clazz.getDeclaredFields())
            .filter(
                field ->
                    field.isAnnotationPresent(CXColumn.class)
                        && field.isAnnotationPresent(CXId.class))
            .findFirst();

    if (!idFieldOptional.isPresent()) {
      throw new IllegalStateException(
          "Id field must be annotated with @CXId for " + clazz.getName() + " class");
    }

    return idFieldOptional.get();
  }

  /**
   * Get id field using type element generated by annotation processing
   *
   * @param clazz type element generated by annotation processing
   * @throws IllegalStateException when id field does not exist for CX annotated class
   * @return annotated element.field id
   */
  public static Element getIdField(final TypeElement clazz) {

    final Optional<? extends Element> idFieldOptional =
        ClassReflectionTool.getDeclaredFields(clazz).stream()
            .filter(
                field ->
                    field.getAnnotation(CXColumn.class) != null
                        && field.getAnnotation(CXId.class) != null)
            .findFirst();

    if (!idFieldOptional.isPresent()) {
      throw new IllegalStateException(
          "Id field must be annotated with @CXId for " + clazz.getSimpleName() + " class");
    }

    return idFieldOptional.get();
  }

  /**
   * Get path for API main annotations
   *
   * @param clazz java simple class
   * @param annotationClass API annotation with path field
   * @return base path
   */
  public static String getPathFromMainApiAnnotation(
      final TypeElement clazz, final Class<?> annotationClass) {

    if (CXSpringRestCrudApi.class.equals(annotationClass)) {
      String path = clazz.getAnnotation(CXSpringRestCrudApi.class).path();
      return "/CX" + ((path.startsWith("/")) ? path : "/" + path);
    }

    throw new IllegalStateException("No path fetched from annotation " + annotationClass.getName());
  }

  /**
   * Get path for API main annotations
   *
   * @param clazz type element generated by annotation processing
   * @param annotationClass API annotation with path field
   * @param paramName parameter name
   * @return base path
   */
  public static String getPathFromMainApiAnnotation(
      final TypeElement clazz, final Class<?> annotationClass, final String paramName) {

    if (CXSpringRestCrudApi.class.equals(annotationClass)) {
      String path = clazz.getAnnotation(CXSpringRestCrudApi.class).path();
      path = ((path.startsWith("/")) ? path : "/" + path);
      return String.format("/CX%s/{%s}", path, paramName);
    }

    throw new IllegalStateException("No path fetched from annotation " + annotationClass.getName());
  }

  /**
   * Get class name based on package and class name
   *
   * @param packageName package name as string
   * @param simpleName class name as string
   * @return ClassName instance based on parameters
   */
  public static ClassName getClassNameFromClassName(
      final String packageName, final String simpleName) {
    return ClassName.get(packageName, simpleName);
  }

  /**
   * Get field from class with attr name
   *
   * @param clazz target class
   * @param attributeName attr name
   * @return field with the same as attributeName param
   */
  public static Field getFieldWithName(Class<?> clazz, final String attributeName) {
    Field[] fields = clazz.getDeclaredFields();
    for (Field field : fields) {
      if (field.getName().equals(attributeName)) return field;
    }
    return null;
  }
}
